#! /bin/bash
# The MIT License
# 
# Copyright 2013 Eric VILLARD <dev@eviweb.fr>.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

usage() {
    echo "usage: git ignore unregister <name>"
    echo ""
    echo "Mandatory Parameters :"
    echo "  <name>  name identifier of the repository to unregister, spaces are not allowed"
    echo ""
}

parse_args() {
    # parse options
    FLAGS "$@" || exit $?
    eval set -- "${FLAGS_ARGV}"

    # save file and patterns in a global variable
    NAME=$1
}

cmd_default() {
    cmd_unregister "$@"
}

cmd_unregister() {
    parse_args "$@"

    # check provided values
    [[ -n $NAME ]] || (echo "!!! Name could not be empty !!!" && echo "" && usage && exit 1)

    # check config file and remove the repository if registered
    FILE=$GITIGNORE_CONFIG_DIR/repositories
    test -e $FILE && sed -i "s#${NAME}\s.*##" $FILE && sed -i "/^$/d" $FILE
}

cmd_help() {
    usage
    exit 0
}