#! /bin/bash
# The MIT License
# 
# Copyright 2013 Eric VILLARD <dev@eviweb.fr>.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

usage() {
    echo ""
    echo "Git ignore help"
    echo ""
	echo "usage: git ignore <subcommand>"
	echo
	echo "Available subcommands are:"
	echo "  list        List all available ignore patterns."
    echo "  see         Display the content of one or more patterns."
	echo "  create      Create a git ignore file."
    echo "  remove      Remove a git ignore file."
	echo "  add         Add ignore patterns to an existing ignore file."
	echo "  delete      Delete ignore patterns from an existing ignore file."
    echo "  refresh     Refresh some already set ignore patterns in an existing ignore file."
    echo "  update      Update this tool and its submodules to their last up to date version."
    echo "  register    Register a local gitignore pattern repository."
    echo "  unregister  Unregister a local gitignore pattern repository."
	echo "  help        Display this message."
	echo "  version     Display version information."
	echo
	echo "Try 'git ignore <subcommand> help' for details."
}

cmd_default() {
	usage
	exit 0
}

cmd_help() {
	usage
	exit 0
}