#! /bin/bash
# The MIT License
# 
# Copyright 2013 Eric VILLARD <dev@eviweb.fr>.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

usage() {
    echo "usage: git ignore add <file> <pattern1>[,<pattern2>,...]"
}

parse_args() {
    # parse options
    FLAGS "$@" || exit $?
    eval set -- "${FLAGS_ARGV}"

    # save file and patterns in a global variable
    FILE=$1
    PATTERNS=$2
}

cmd_default() {
    cmd_add "$@"
}

cmd_add() {
    parse_args "$@"

    if [[ ! -f $FILE ]]; then
        echo "File not found : $FILE"
        exit 1
    fi

    declare -a patterns=( $(splitpatterns "$PATTERNS") )
    for pattern in "${patterns[@]}"; do 
 #       if ! ispatterninfile $pattern $FILE; then
 #           getpatternsfromfile "$pattern" >> $FILE
 #       fi
echo "-----------------"
echo "$pattern -> $FILE"
if ispatterninfile $pattern $FILE; then
    echo "IN"
else 
    echo "NO"
fi
echo "-------------------"
    done
    #normalizecontent $content >> $FILE
}

cmd_help() {
    usage
    exit 0
}