#! /bin/bash
# The MIT License
# 
# Copyright 2013 Eric VILLARD <dev@eviweb.fr>.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

usage() {
    echo ""
    echo "Update this tool and its submodules to their last up to date version."
    echo ""
    echo "usage: git ignore update"
    echo ""
}

cmd_default() {
    cmd_update "$@"
}

cmd_update() {
    BACKUP_DIR=`pwd`
    cd $GITIGNORE_DIR
    git fetch --all --recurse-submodules=yes
    git submodule foreach git rebase -r origin/master
    git rebase -r origin/master
    #
    local repos=( $(getgitrepos) )
    for repo in ${repos[@]}
    do
        cd $repo
        local remotebranch=$(git rev-parse --abbrev-ref --symbolic-full-name @{u} 2> /dev/null)
        local split=( ${remotebranch//\// } )
        local remote=${split[0]}

        if [ $remotebranch != "@{u}" ]
        then
            git fetch $remote
            git rebase -r $remotebranch
        fi        
    done
    cd $BACKUP_DIR
}

cmd_help() {
    usage
    exit 0
}