#! /bin/bash
# The MIT License
# 
# Copyright 2013 Eric VILLARD <dev@eviweb.fr>.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

export GITIGNORE_SRC=$GITIGNORE_DIR/vendor/github/gitignore

# shell output
warn() { echo "$@" >&2; }
die() { warn "$@"; exit 1; }

escape() {
    echo "$1" | sed 's/\([\.\$\*]\)/\\\1/g'
}

# set logic
has() {
    local item=$1; shift
    echo " $@ " | grep -q " $(escape $item) "
}

# basic string matching
startswith() { [ "$1" != "${1#$2}" ]; }
endswith() { [ "$1" != "${1%$2}" ]; }

# convenience functions for checking shFlags flags
flag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -eq $FLAGS_TRUE ]; }
noflag() { local FLAG; eval FLAG='$FLAGS_'$1; [ $FLAG -ne $FLAGS_TRUE ]; }

# print array elements using column format
printcolumn() {
    declare -a values=($@)
    for value in "${values[@]}"; do 
        printf "%-8s\n" "${value}"
    done | column
}

# list *.gitignore files
listgitignores() {
    local pattern="\.gitignore"
    ls $1 | grep $pattern | sed "s/$pattern//g"
}

# split pattern list
splitpatterns() {
    local patterns=$1
    echo ${patterns//,/ }
}

# merge pattern file
mergepatterns() {
    declare -a patterns=( $(splitpatterns "$1") )
    local merged=""
    for pattern in "${patterns[@]}"; do 
        local file="$GITIGNORE_SRC/$pattern.gitignore"
        if [[ ! -e $file ]]; then
            file="$GITIGNORE_SRC/Global/$pattern.gitignore"
        fi
        if [[ -e $file ]]; then
            merged="$merged\n$(cat $file)"
        fi
    done
    echo -e $merged
}

# normalize file content
normalizecontent() {
    echo -e "$@" | sed "s/ /\n/g"
}